# Project information
site_name: Leslie's Online Notebook
site_description:
site_author: 'Leslie'
site_url: 'https://leslieclif.github.io/notebook/'

# Docs dir
docs_dir: './docs/'

# Repository
repo_name: 'notebook'

# Copyright
copyright: 'Copyright &copy; 2018 - 2019 Leslie'

nav:
  - Home: 
      - index.md
      - Setup: developer.md
  - Server:
      - server/index.md
      - Installation: server/install.md
      - Mobile: server/mobile.md
  - Devops:
      - devops/index.md
  - Kubernetes:
      - k8s/index.md
      - Installation: k8s/install.md
  - IDE:
      - ide/index.md
      - Markdown: ide/markdown.md
  - Learning:
      - Git: learning/git.md
      - Python: learning/python.md
      - Vagrant: learning/vagrant.md
      - Ansible: learning/ansible.md
      - Terraform: learning/terraform.md
      - Docker: learning/docker/docker-notes.md
      - Kubernetes: learning/k8s/k8s-notes.md
     

# Theme
theme:
  name: 'material'
  language: 'en'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  feature:
    - navigation.tabs
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - toc.integrate
  palette:
    #primary: 'indigo'
    #accent: 'indigo'
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
# Desirable to hide the navigation and/or table of contents sidebar,
# especially when there's a single navigation item. 
hide:
  - navigation # Hide navigation
  - toc        # Hide table of contents
# Extensions
markdown_extensions:
  - toc:
      permalink: True
      toc_depth: 3
      slugify: !!python/name:pymdownx.slugs.uslugify_cased
  - admonition
  - footnotes
  - meta
  - codehilite
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tilde