# Project information
site_name: Leslie's Online Notebook
site_description:
site_author: 'Leslie'
site_url: 'https://leslieclif.github.io/notebook/'

# Docs dir
docs_dir: './docs/'

# Repository
repo_name: 'notebook'

# Copyright
copyright: 'Copyright &copy; 2018 - 2019 Leslie'

nav:
  - Home:
      - Welcome: index.md
      - Setup: developer.md
  - Server:
      - Introduction: server/index.md
      - Installation: server/install.md
      - Mobile: server/mobile.md
  - Devops:
      - Introduction: devops/index.md
  - Kubernetes:
      - Introduction: k8s/index.md
      - Installation: k8s/install.md
  - IDE:
      - Introduction: ide/index.md
      - Markdown: ide/markdown.md
  - Learning:
      - Git: learning/git.md
      - Python: learning/python.md
      - Vagrant: learning/vagrant.md
      - Ansible: learning/ansible.md
      - Terraform: learning/terraform.md
      - Docker: learning/docker/docker-notes.md
      - Kubernetes: learning/k8s/k8s-notes.md
     

# Theme
theme:
  name: 'material'
  language: 'en'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  feature:
    tabs: true
  palette:
    primary: 'indigo'
    accent: 'indigo'

# Extensions
markdown_extensions:
  - admonition
  - footnotes
  - meta
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tilde