# Project information
site_name: Leslie's Online Notebook
site_description:
site_author: 'Leslie'
site_url: 'https://leslieclif.github.io/notebook/'

# Docs dir
docs_dir: './docs/'

# Repository
repo_name: 'notebook'

# Copyright
copyright: 'Copyright &copy; 2018 - 2019 Leslie'

# Navigation  
nav:
  - Home: 
    - Installation: index.md
    - Developer Setup: developer.md
  - Devops:
    - devops/index.md
    - CI: devops/ci.md
    - CD: devops/cd.md
    - IAC: devops/iac.md
    - GitOps: devops/gitops.md
    - Skills: devops/devops-engineer.md
  - IDE:
    - ide/index.md
    - Markdown: ide/markdown.md
  - Server:
    - server/index.md
    - Installation: server/install.md
    - Mobile: server/mobile.md    
  - Ansible:
    - Ansible: learning/ansible/ansible.md
  - Kubernetes:
    - k8s/index.md
    - Installation: k8s/install.md
  - Learning:
    - Git: learning/git.md
    - Python: learning/python.md
    - Vagrant: learning/vagrant.md
    - Terraform: learning/terraform.md
    - Docker: learning/docker/docker-notes.md
    - Kubernetes: learning/k8s/k8s-notes.md
    - Linux: learning/linux/linux.md
    - Linux_Security: learning/linux/security.md   
     
# Theme
theme:
  name: 'material'
  language: 'en'
  icon:
    logo: material/book-open-page-variant
  custom_dir: docs/assets
  palette:
  # Dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: deep blue
    accent: yellow
    toggle:
      icon: material/lightbulb
      name: Switch to light mode
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  feature:
    - navigation.tabs
    - navigation.tabs.sticky
  highlightjs: true
  hljs_languages:
      - yaml
  navigation_depth: 3

extra_css:
 - assets/extra.css
# extra_javascript:
#   - assets/termynal.js
# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Extensions
markdown_extensions:
  - admonition
  - footnotes
  - meta
  - codehilite
  - markdown.extensions.toc:
      slugify: !!python/name:pymdownx.slugs.uslugify
      permalink: true
      baselevel: 2
  - markdown.extensions.admonition:
  - markdown.extensions.smarty:
      smart_quotes: false
  - pymdownx.betterem:
  - markdown.extensions.attr_list:
  - markdown.extensions.def_list:
  - markdown.extensions.tables:
  - markdown.extensions.abbr:
  - markdown.extensions.footnotes:
  - markdown.extensions.md_in_html:
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.highlight:
      extend_pygments_lang:
        - name: php-inline
          lang: php
          options:
            startinline: true
        - name: pycon3
          lang: pycon
          options:
            python3: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite:
      custom_inline:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.inline_mathjax_format
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
      social_url_shortener: true
      user: facelessuser
      repo: pymdown-extensions
  - pymdownx.tilde:
  - pymdownx.critic:
  - pymdownx.details:
  - pymdownx.caret:
  - pymdownx.smartsymbols:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.escapeall:
      hardbreak: True
      nbsp: True
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.progressbar:
  - pymdownx.arithmatex:
  - pymdownx.mark:
  - pymdownx.striphtml:
  - pymdownx.snippets:
      base_path: docs/src/markdown/_snippets
  - pymdownx.keys:
      separator: "\uff0b"
  - pymdownx.tabbed:
  - pymdownx.saneheaders:
